import flet as ft


HOME = ft.Icons.HOME_ROUNDED

TRANSLATE = ft.Icons.TRANSLATE_ROUNDED

IMAGE = ft.Icons.IMAGE_ROUNDED

MIC = ft.Icons.MIC_ROUNDED

DESCRIPTION = ft.Icons.DESCRIPTION_ROUNDED

SETTINGS = ft.Icons.SETTINGS_ROUNDED

DARK = ft.Icons.DARK_MODE_ROUNDED

LIGHT = ft.Icons.LIGHT_MODE_ROUNDED